### ISSUE TITLE
Problème url bloc liens

### ISSUE THREAD

**Issue by justinpuyo** [noesya/bordeauxmontaigne-iut#100]
Dans le bloc lien, il semble que le champ url subisse un traitement qui traduit les caractères spéciaux en html.
J'ai un cas où ça pose problème sur la page [Scolarité](https://www.iut.u-bordeaux-montaigne.fr/formation/scolarite/#le-service-scolarite)
J'ai un "&" dans l'url du lien SOS Scolarité IUT.
Du coup https://intranet.u-bordeaux-montaigne.fr/rita_fo/?num_cg=16&num_form=1
devient https://intranet.u-bordeaux-montaigne.fr/rita_fo/?num_cg=16&amp;num_form=1
et mon lien ne marche plus 😕

**Comment by justinpuyo** [comment]
Ça fait pareil sur les boutons des blocs CTA.
En attendant j'ai mis mon lien dans un bloc chapitre.

**Comment by arnaudlevy** [comment]
@Olivia206 je livre ça dans le yaml
```yaml
      links:
        - title: >-
            Test

          description: >-
            

          url: >-
            https://intranet.u-bordeaux-montaigne.fr/rita_fo/?num_cg=16&amp;num_form=1

          external: true
```

Est-ce que je fais qqch de mon côté, ou toi du tien ?
